### PR TITLE
Revamp repository for AGU and future work

### PR DESCRIPTION
**Pull request by bpbond**
**DO NOT MERGE YET**

Opening this PR so @AditiGit can easily track ongoing changes.

### CODE REVIEW

**Comment by AditiGit** [comment]
Ok. sounds good.

**Review by AditiGit — APPROVED** [review]
Sounds good. will keep an eye on the workflow.

**Comment by bpbond** [comment]
@AditiGit here's a snapshot of the current matching process, which we have to do before computing fluxes.

* `1956 of 1991 valve key entries were matched` - so most of your entries in the `ValveMap` sheet (in the repository, saved as `gs_valvemap.csv`) have associated entries in the Picarro data (same valve number and matching the timestamp range).
* `  167476 of 859514 Picarro data entries were matched` - lots of Picarro data were _not_ matched. This might be OK, if for example the machine was left running a lot between measurements.

Here's a visualization of the first of those bullets:

qc_match

On the x axis is time; y axis is valve number; light dots are good (found matching Picarro data), while black dots are 'bad': there's an entry in the valve map file, but the script couldn't find any Picarro data for it. Thoughts? Probably the most concerning thing to me is that cluster of dark dots in late August--lots of unmatched data.

**Comment by bpbond** [comment]
Moved the matching questions to #8 - better place for it.

**Pull request closed without merging**
